### ISSUE TITLE
CTD when loading

### ISSUE THREAD

**Issue by Swootch** [dissociativity/PKs_Rebalancing#18]
Starting a game with PKs Rebalancing causes a CTD during loading:
![Untitled](https://user-images.githubusercontent.com/45204409/60365875-33163080-99ea-11e9-9776-ef47c43e1161.png)

![Untitled2](https://user-images.githubusercontent.com/45204409/60365948-783a6280-99ea-11e9-8010-d5eb2fe7cf59.png)

![Untitled3](https://user-images.githubusercontent.com/45204409/60365958-7a9cbc80-99ea-11e9-875b-ce069f35606b.png)

anothersimulacrum on the discord said it's as easy as deleting the NO_ROTATE flag from the corresponding object, but when I do it, it just causes more errors.

**Comment by sdp0et** [comment]
I opened this issue in the main CDDA repo: https://github.com/CleverRaven/Cataclysm-DDA/issues/31897

They closed it saying it was due to PK and/or Arcana, which both use the terrain I used as an example "strange_cabin"/"strange_cabin_north".  I made some assumptions about what was going on and stepped through each error as it occurred and changed the pk mod files and it seems to work.

@Bulletfang I had to make two types of changes.

for each invalid terrain reference 
- See if the terrain is overridden in pk_overmap_terrain.json, if so remove the NO_ROTATE flag (I removed the whole line, not just the flag itself).
- also check in pk_overmap for any references to that terrain id in the overmap_special definitions and append a direction ( chose "_north" because that's what I saw in the core json files, but I really am not sure if it's correct in all cases)  ex: "overmap": "campsite_a" to "overmap": "campsite_a_north"

There were a a handful of changes in each file, but not every id references in pk_overmap.json was overridden in in pk_overmap_terrain.json.

I don't know if it "works" but I am at least able to generate a world without a CTD.

**Comment by dissociativity** [comment]
attempted a fix, I'm not expert though, so let me know how it is now in the latest version from the github zip (not other the releases tab, just download zip, I'm sure you're smart and know this but others have made the mistake of only using the releases tab before)

**Comment by roaringjohn** [comment]
Everything is broken now.
[debug.log](https://github.com/dissociativity/PKs_Rebalancing/files/3346939/debug.log)

**Comment by dissociativity** [comment]
fixed!
